import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
import Servise from "./components/Services";
import About from "./components/About";
import Secstion from "./components/Secstion";
import Fact from "./components/Facts";
import Client from "./components/Clients";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Servise />
      <About />
      <Secstion />
      <Fact />
      <Client />
      <Footer />
    </>
  );
}
